version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        container_name: django-api
        volumes:
            - ./dynamic-blog-api:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8000"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            - mailhog
            - redis
        networks:
            - dynamic-blog-network

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        container_name: postgres
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - dynamic-blog-network

    mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        ports:
            - "8025:8025"
        networks:
            - dynamic-blog-network

    nginx:
        build:
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        restart: always
        container_name: nginx
        depends_on:
            - api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8080:80"
        networks:
            - dynamic-blog-network

    redis:
        image: redis:6-alpine
        container_name: redis
        networks:
            - dynamic-blog-network
    
    celery_worker:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: '/start-celeryworker'
        container_name: celeryworker
        volumes:
            - .:/app
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - redis
            - postgres
            - mailhog
        networks:
            - dynamic-blog-network
    
    flower:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: '/start-flower'
        container_name: flower
        volumes:
            - .:/app
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - redis
            - postgres
        ports:
            - "5555:5555"
        networks:
            - dynamic-blog-network


networks:
    dynamic-blog-network:
        driver: bridge

    
volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    static_volume:
    media_volume: