# Generated by Django 4.0.5 on 2022-06-24 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('about_me', models.TextField(default='Say something about yourself...', verbose_name='About me')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('n/a', 'n/a')], default='n/a', max_length=10, verbose_name='Gender')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(default='+919999999999', max_length=13, region=None, verbose_name='Phonenumber')),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('profile_pic', models.ImageField(default='', upload_to='')),
                ('twitter_handle', models.CharField(blank=True, max_length=20, verbose_name='Twitter Handle')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
                'abstract': False,
            },
        ),
    ]
